postgres:
  username: postgres
  password: postgres
  database: petwise
  url: localhost:5432

# Keycloak local instance
keycloak:
  issuer-uri: http://localhost:9080/realms/petwise

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2