version: '3.7'

services:
  db:
    container_name: petwise-postgresql
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petwise
    ports:
      - 5432:5432