version: '3.7'

services:
  db:
    container_name: petwise-postgresql
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petwise
    ports:
      - 5432:5432
    networks:
      - petwise_network
  app:
    container_name: petwise-springboot-app
    image: ghcr.io/${GITHUB_REPOSITORY:-petwise/petwise}:${PETWISE_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always
    networks:
      - petwise_network
networks:
  petwise_network: