[versions]
spring-boot = "3.5.7"
spotless = "8.0.0"
spring-dependency-management = "1.1.7"
junit = "5.10.2"
postgresql = "42.7.8"

[libraries]
# Spring Boot Starters
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-undertow = { module = "org.springframework.boot:spring-boot-starter-undertow", version.ref = "spring-boot" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "spring-boot" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }

postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql"}
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

# Plugins
spring-boot-gradle = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }
io-spring-dependency-management-gradle = { module = "io.spring.dependency-management:io.spring.dependency-management.gradle.plugin", version.ref = "spring-dependency-management" }
spotless-gradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

[bundles]
spring-boot-starter = ["spring-boot-starter-validation", "spring-boot-starter-data-jpa"]
spring-boot-starter-test = ["spring-boot-starter-test"]

[plugins]
spring-boot-app-convention = { id = "petwise.spring-boot-app-conventions" }
java-library-convention = { id = "petwise.java-library-conventions" }
jacoco-aggregation-convention = { id = "petwise.jacoco-aggregation-conventions" }
